--- # playbook3.yml
  - hosts: webserver1
    user: ansible
    become: yes
    connection: ssh

    name: This is our first play

    tasks:
       - name: Create a dummy directory  on webserver1
         command: mkdir -p  /tmp/ansible_dummy_dir

  
