
--- #My Target Section 
  - hosts: demo
    user: ansible
    become: yes
    connection: ssh
    
    tasks:
    - name: install httpd server on amazon linux
      action: yum name=httpd state=installed






