
--- # Handler Section
  - hosts: demo
    user: ansible
    become: yes
    connection: ssh
  
    tasks:
      - name: install httpd on amazon linux
        action: yum name=httpd state=installed
        notify: restart httpd
        
    handlers:
      - name: restart httpd
        action: service name=httpd state=restarted
      


