--- # lamp_playbook.yml
  - name: Installing Apache in Amazon Linux
    hosts: sqlserver1
    user: ansible
    become: yes
    connection: ssh

    tasks:

      - name: Uninstall previous installed apache httpd 
        command: yum remove httpd* -y

      - name: Remove /var/www/html content
        command:  rm -rf /var/www/html/
        become: true

      - name: Remove /tmp wordpress content
        command: rm -rf /tmp/wordpress.tar.gz
      
      - name: Uninstall previous installed  mysql-server
        command: yum remove mysql-server -y

      - name: Uninstall previous installed  mysql
        command: yum remove mysql -y

      - name: Remove /tmp mysql-server content
        command: rm -rf /tmp/mysql-community-release-el7-7.noarch.rpm

      - name: PHP7.2  Installation
        command: amazon-linux-extras install -y  php7.2
 
      - name: Apach httpd  Installation
        yum: name=httpd state=latest

      - name: Download wordpress
        get_url:
           url: https://wordpress.org/latest.tar.gz
           dest: /tmp/wordpress.tar.gz
           validate_certs: no

      - name: Extract wordpress package
        unarchive: src=/tmp/wordpress.tar.gz  dest=/var/www/html/ remote_src=yes

      - name: Copy Wordpress files to /var/www/html location
        command: cp -r /var/www/html/wordpress/.  /var/www/html/ 

      - name: Remove wordpress directory
        command: rm -rf /var/www/html/wordpress

      - name: Remove wordpress package
        command: rm -rf /var/www/html/latest.tar.gz
      
      - name: Chage wp-content permissions
        file:
            path: /var/www/html/wp-content
            owner: apache
            group: apache
            mode: 0755

      - name: Enable and Start the Apache Httpd Service
        service: 
          name: httpd 
          state: started  
          enabled: yes

      - name: Download MySQL Community Repo
        get_url:
           url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
           dest: /tmp

      - name: Install MySQL Repo through RPM
        yum: name=/tmp/mysql-community-release-el7-7.noarch.rpm state=present

      - name: Install MySQL Server packages
        yum: name=mysql-server state=present

      - name: Install Python
        yum:
            name: python
            state: latest

      - name: Install MYSQL-python
        yum: name=MySQL-python state=present

      - name: Start MySQL Server and enable it
        service:
           name: mysqld
           state: started
           enabled: yes
           
      - name: Remove Test database if it exist.
        mysql_db:
           name: test
           state: absent

      - name: Remove All Anonymous User Accounts
        mysql_user:
           name: ''
           host_all: yes
           state: absent

      - name: Create MySQL Server database user with  all database privileges
        mysql_user:
           name: user
           password: user123
           priv: '*.*:ALL'
           state: present

      - name: Create MySQL Server  new database with name 'wordpressdb'
        mysql_db:
           name: wordpressdb
           state: present

      - name: Restart MySQL Server
        service:
           name: mysqld
           state: restarted
 
      
