--- # larger_playbook.yml
  - hosts: webserver1
    user: ansible
    become: yes
    connection: ssh

    name: This is our first play

    vars:
            var1: var1
            var2: var2
            var3: var3
            var4: var4

    tasks:
      - name: Create large directory on webserver1
        command: mkdir /tmp/large


      - name: Task1 on webserver1
        command: touch /tmp/large/{{ var1 }}.txt

      - name: Task2 on webserver1
        command: touch /tmp/large/{{ var2 }}.txt

      - name: Task3 on webserver1
        command: touch /tmp/large/{{ var3 }}.txt

      - name: Task4 on webserver1
        command: touch /tmp/large/{{ var4 }}.txt
  



